{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Test interact with CLickhouse and HDFS"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "from clickhouse_driver import Client\n",
    "import pandas as pd\n",
    "import os\n",
    "from dotenv import load_dotenv"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Clickhouse cloud"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[('INFORMATION_SCHEMA',),\n",
       " ('default',),\n",
       " ('information_schema',),\n",
       " ('mydb',),\n",
       " ('system',)]"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# load env\n",
    "load_dotenv()\n",
    "\n",
    "cloud=os.getenv(\"HOST\")\n",
    "user=os.getenv(\"USERNAME\")\n",
    "password=os.getenv(\"PASS\")\n",
    "port=9440\n",
    "\n",
    "# Connect to database\n",
    "conn = Client(host=cloud, port=port, user=user, password=password, secure='y',verify=False)\n",
    "conn.execute(\"show databases\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [],
   "source": [
    "df = pd.DataFrame([\n",
    "    {'year': 1994, 'first_name': 'Vova'},\n",
    "    {'year': 1995, 'first_name': 'Anja'},\n",
    "    {'year': 1996, 'first_name': 'Vasja'},\n",
    "    {'year': 1997, 'first_name': 'Petja'},\n",
    "    {'year': 2000, 'first_name': 'Petja'},\n",
    "    {'year': 2131, 'first_name': 'Petja'},\n",
    "])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Create database mydb\n",
      "done...\n",
      "Created table mydb.test\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    print('Create database mydb')\n",
    "    conn.execute('create database if not exists mydb')\n",
    "    print('done...')\n",
    "    conn.execute('''\n",
    "    create table if not exists mydb.test(\n",
    "        year Int,\n",
    "        first_name String\n",
    "    ) engine = Memory\n",
    "    ''')\n",
    "    print('Created table mydb.test')\n",
    "except Exception as e:\n",
    "    print(e)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "done pussing 6 into test table\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    row = conn.execute(\"insert into mydb.test values\", df.to_dict('records'))\n",
    "    print(f'done pussing {row} into test table')\n",
    "except Exception as e:\n",
    "    print(e)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[(1994, 'Vova'),\n",
       " (1995, 'Anja'),\n",
       " (1996, 'Vasja'),\n",
       " (1997, 'Petja'),\n",
       " (2000, 'Petja'),\n",
       " (2131, 'Petja')]"
      ]
     },
     "execution_count": 16,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "conn.execute('select * from mydb.test')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Local"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "conn = Client('localhost')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[('INFORMATION_SCHEMA',),\n",
       " ('default',),\n",
       " ('information_schema',),\n",
       " ('system',),\n",
       " ('testdb',)]"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "conn.execute(\"show databases\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "create table ny_taxi_data\n",
      "Done...\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    print(\"create table ny_taxi_data\")\n",
    "    conn.execute(\"\"\"\n",
    "    CREATE TABLE IF NOT EXISTS yellow_taxi_data (\n",
    "\t\"VendorID\" BIGINT, \n",
    "\ttpep_pickup_datetime TIMESTAMP, \n",
    "\ttpep_dropoff_datetime TIMESTAMP, \n",
    "\tpassenger_count FLOAT(53), \n",
    "\ttrip_distance FLOAT(53), \n",
    "\t\"RatecodeID\" FLOAT(53), \n",
    "\tstore_and_fwd_flag TEXT, \n",
    "\t\"PULocationID\" BIGINT, \n",
    "\t\"DOLocationID\" BIGINT, \n",
    "\tpayment_type BIGINT, \n",
    "\tfare_amount FLOAT(53), \n",
    "\textra FLOAT(53), \n",
    "\tmta_tax FLOAT(53), \n",
    "\ttip_amount FLOAT(53), \n",
    "\ttolls_amount FLOAT(53), \n",
    "\timprovement_surcharge FLOAT(53), \n",
    "\ttotal_amount FLOAT(53), \n",
    "\tcongestion_surcharge FLOAT(53), \n",
    "\tairport_fee FLOAT(53)\n",
    ") ENGINE = Memory\n",
    "\"\"\")\n",
    "    print('Done...')\n",
    "except Exception as e:\n",
    "    print(e)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## HDFS"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[]"
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "from hdfs3 import HDFileSystem\n",
    "port = 8020\n",
    "hdfs = HDFileSystem('localhost', port)\n",
    "hdfs.ls('/')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "ename": "OSError",
     "evalue": "Prior attempt to load libhdfs failed",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mOSError\u001b[0m                                   Traceback (most recent call last)",
      "\u001b[1;32m/home/phonghuynh/Desktop/Tech/DE_bootcamp/week_2/clickhouse-connect.ipynb Cell 15\u001b[0m line \u001b[0;36m3\n\u001b[1;32m      <a href='vscode-notebook-cell://wsl%2Bubuntu-22.04/home/phonghuynh/Desktop/Tech/DE_bootcamp/week_2/clickhouse-connect.ipynb#X26sdnNjb2RlLXJlbW90ZQ%3D%3D?line=0'>1</a>\u001b[0m \u001b[39mimport\u001b[39;00m \u001b[39mdask\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mdataframe\u001b[39;00m \u001b[39mas\u001b[39;00m \u001b[39mdd\u001b[39;00m\n\u001b[1;32m      <a href='vscode-notebook-cell://wsl%2Bubuntu-22.04/home/phonghuynh/Desktop/Tech/DE_bootcamp/week_2/clickhouse-connect.ipynb#X26sdnNjb2RlLXJlbW90ZQ%3D%3D?line=1'>2</a>\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mpyarrow\u001b[39;00m \u001b[39mimport\u001b[39;00m fs\n\u001b[0;32m----> <a href='vscode-notebook-cell://wsl%2Bubuntu-22.04/home/phonghuynh/Desktop/Tech/DE_bootcamp/week_2/clickhouse-connect.ipynb#X26sdnNjb2RlLXJlbW90ZQ%3D%3D?line=2'>3</a>\u001b[0m hdfs \u001b[39m=\u001b[39m fs\u001b[39m.\u001b[39;49mHadoopFileSystem(\u001b[39m'\u001b[39;49m\u001b[39mlocalhost\u001b[39;49m\u001b[39m'\u001b[39;49m, \u001b[39m8020\u001b[39;49m)\n",
      "File \u001b[0;32m~/miniconda3/envs/dask/lib/python3.9/site-packages/pyarrow/_hdfs.pyx:96\u001b[0m, in \u001b[0;36mpyarrow._hdfs.HadoopFileSystem.__init__\u001b[0;34m()\u001b[0m\n",
      "File \u001b[0;32m~/miniconda3/envs/dask/lib/python3.9/site-packages/pyarrow/error.pxi:144\u001b[0m, in \u001b[0;36mpyarrow.lib.pyarrow_internal_check_status\u001b[0;34m()\u001b[0m\n",
      "File \u001b[0;32m~/miniconda3/envs/dask/lib/python3.9/site-packages/pyarrow/error.pxi:115\u001b[0m, in \u001b[0;36mpyarrow.lib.check_status\u001b[0;34m()\u001b[0m\n",
      "\u001b[0;31mOSError\u001b[0m: Prior attempt to load libhdfs failed"
     ]
    }
   ],
   "source": [
    "import dask.dataframe as dd\n",
    "from pyarrow import fs\n",
    "hdfs = fs.HadoopFileSystem('localhost', 8020)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "{'capacity': 1081101176832, 'used': 45056, 'percent-free': 99.99999583239747}"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "hdfs.df()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "hdfs.mkdir('hello')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "ename": "OSError",
     "evalue": "Could not open file: /requirements.txt, mode: wb Permission denied: user=phonghuynh, access=WRITE, inode=\"/\":root:supergroup:drwxr-xr-x",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mOSError\u001b[0m                                   Traceback (most recent call last)",
      "\u001b[1;32m/home/phonghuynh/Desktop/Tech/DE_bootcamp/week_2/clickhouse-connect.ipynb Cell 17\u001b[0m line \u001b[0;36m1\n\u001b[0;32m----> <a href='vscode-notebook-cell://wsl%2Bubuntu-22.04/home/phonghuynh/Desktop/Tech/DE_bootcamp/week_2/clickhouse-connect.ipynb#X22sdnNjb2RlLXJlbW90ZQ%3D%3D?line=0'>1</a>\u001b[0m hdfs\u001b[39m.\u001b[39;49mput(\u001b[39m'\u001b[39;49m\u001b[39mrequirements.txt\u001b[39;49m\u001b[39m'\u001b[39;49m, \u001b[39m'\u001b[39;49m\u001b[39m/requirements.txt\u001b[39;49m\u001b[39m'\u001b[39;49m)\n",
      "File \u001b[0;32m~/miniconda3/envs/hdfs/lib/python3.8/site-packages/hdfs3/core.py:578\u001b[0m, in \u001b[0;36mHDFileSystem.put\u001b[0;34m(self, filename, path, chunk, replication, block_size)\u001b[0m\n\u001b[1;32m    576\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mput\u001b[39m(\u001b[39mself\u001b[39m, filename, path, chunk\u001b[39m=\u001b[39mDEFAULT_WRITE_BUFFER_SIZE, replication\u001b[39m=\u001b[39m\u001b[39m0\u001b[39m, block_size\u001b[39m=\u001b[39m\u001b[39m0\u001b[39m):\n\u001b[1;32m    577\u001b[0m \u001b[39m    \u001b[39m\u001b[39m\"\"\" Copy local file to path in HDFS \"\"\"\u001b[39;00m\n\u001b[0;32m--> 578\u001b[0m     \u001b[39mwith\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mopen(path, \u001b[39m'\u001b[39;49m\u001b[39mwb\u001b[39;49m\u001b[39m'\u001b[39;49m, replication\u001b[39m=\u001b[39;49mreplication,\n\u001b[1;32m    579\u001b[0m                    block_size\u001b[39m=\u001b[39;49mblock_size) \u001b[39mas\u001b[39;00m target:\n\u001b[1;32m    580\u001b[0m         \u001b[39mwith\u001b[39;00m \u001b[39mopen\u001b[39m(filename, \u001b[39m'\u001b[39m\u001b[39mrb\u001b[39m\u001b[39m'\u001b[39m) \u001b[39mas\u001b[39;00m source:\n\u001b[1;32m    581\u001b[0m             \u001b[39mwhile\u001b[39;00m \u001b[39mTrue\u001b[39;00m:\n",
      "File \u001b[0;32m~/miniconda3/envs/hdfs/lib/python3.8/site-packages/hdfs3/core.py:249\u001b[0m, in \u001b[0;36mHDFileSystem.open\u001b[0;34m(self, path, mode, replication, buff, block_size)\u001b[0m\n\u001b[1;32m    246\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39m'\u001b[39m\u001b[39mb\u001b[39m\u001b[39m'\u001b[39m \u001b[39mnot\u001b[39;00m \u001b[39min\u001b[39;00m mode:\n\u001b[1;32m    247\u001b[0m     \u001b[39mraise\u001b[39;00m \u001b[39mNotImplementedError\u001b[39;00m(\u001b[39m\"\u001b[39m\u001b[39mText mode not supported, use mode=\u001b[39m\u001b[39m'\u001b[39m\u001b[39m%s\u001b[39;00m\u001b[39m'\u001b[39m\u001b[39m\"\u001b[39m\n\u001b[1;32m    248\u001b[0m                               \u001b[39m\"\u001b[39m\u001b[39m and manage bytes\u001b[39m\u001b[39m\"\u001b[39m \u001b[39m%\u001b[39m (mode \u001b[39m+\u001b[39m \u001b[39m'\u001b[39m\u001b[39mb\u001b[39m\u001b[39m'\u001b[39m))\n\u001b[0;32m--> 249\u001b[0m \u001b[39mreturn\u001b[39;00m HDFile(\u001b[39mself\u001b[39;49m, path, mode, replication\u001b[39m=\u001b[39;49mreplication, buff\u001b[39m=\u001b[39;49mbuff,\n\u001b[1;32m    250\u001b[0m               block_size\u001b[39m=\u001b[39;49mblock_size)\n",
      "File \u001b[0;32m~/miniconda3/envs/hdfs/lib/python3.8/site-packages/hdfs3/core.py:706\u001b[0m, in \u001b[0;36mHDFile.__init__\u001b[0;34m(self, fs, path, mode, replication, buff, block_size)\u001b[0m\n\u001b[1;32m    704\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mblock_size \u001b[39m=\u001b[39m block_size\n\u001b[1;32m    705\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mlines \u001b[39m=\u001b[39m deque([])\n\u001b[0;32m--> 706\u001b[0m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_set_handle()\n\u001b[1;32m    707\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39msize \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39minfo()[\u001b[39m'\u001b[39m\u001b[39msize\u001b[39m\u001b[39m'\u001b[39m]\n",
      "File \u001b[0;32m~/miniconda3/envs/hdfs/lib/python3.8/site-packages/hdfs3/core.py:716\u001b[0m, in \u001b[0;36mHDFile._set_handle\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    714\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m out:\n\u001b[1;32m    715\u001b[0m     msg \u001b[39m=\u001b[39m ensure_string(_lib\u001b[39m.\u001b[39mhdfsGetLastError())\u001b[39m.\u001b[39msplit(\u001b[39m'\u001b[39m\u001b[39m\\n\u001b[39;00m\u001b[39m'\u001b[39m)[\u001b[39m0\u001b[39m]\n\u001b[0;32m--> 716\u001b[0m     \u001b[39mraise\u001b[39;00m \u001b[39mIOError\u001b[39;00m(\u001b[39m\"\u001b[39m\u001b[39mCould not open file: \u001b[39m\u001b[39m%s\u001b[39;00m\u001b[39m, mode: \u001b[39m\u001b[39m%s\u001b[39;00m\u001b[39m \u001b[39m\u001b[39m%s\u001b[39;00m\u001b[39m\"\u001b[39m \u001b[39m%\u001b[39m\n\u001b[1;32m    717\u001b[0m                   (\u001b[39mself\u001b[39m\u001b[39m.\u001b[39mpath, \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mmode, msg))\n\u001b[1;32m    718\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_handle \u001b[39m=\u001b[39m out\n",
      "\u001b[0;31mOSError\u001b[0m: Could not open file: /requirements.txt, mode: wb Permission denied: user=phonghuynh, access=WRITE, inode=\"/\":root:supergroup:drwxr-xr-x"
     ]
    }
   ],
   "source": [
    "hdfs.put('requirements.txt', '/requirements.txt')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-09-28 15:40:03.883973, p680, th139982298342464, ERROR Failed to setup the pipeline for new block [block pool ID: BP-435783800-172.19.0.4-1695890191831 block ID 1073741825_1001] file /test.txt.\n",
      "Pipeline.cpp: 700: HdfsIOException: Cannot create block output stream for block [block pool ID: BP-435783800-172.19.0.4-1695890191831 block ID 1073741825_1001], recovery flag: false, with last generate stamp 0.\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tffi_closure_alloc\n",
      "\t@\tdlfree\n",
      "\t@\tdlmmap.constprop.0\n",
      "\t@\tu_set\n",
      "\t@\tUnknown\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tPyEval_EvalCodeEx\n",
      "\t@\tPyEval_EvalCode\n",
      "\t@\tbuiltin_exec\n",
      "\t@\tcfunction_vectorcall_FASTCALL\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tmethod_vectorcall_O\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\tPyObject_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\tcontext_run\n",
      "Caused by\n",
      "TcpSocket.cpp: 282: HdfsTimeoutException: Connect to \"172.19.0.3:9866\" timeout\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tffi_closure_alloc\n",
      "\t@\tdlfree\n",
      "\t@\tdlmmap.constprop.0\n",
      "\t@\tu_set\n",
      "\t@\tUnknown\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tPyEval_EvalCodeEx\n",
      "\t@\tPyEval_EvalCode\n",
      "\t@\tbuiltin_exec\n",
      "\t@\tcfunction_vectorcall_FASTCALL\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tmethod_vectorcall_O\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\tPyObject_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tUnknown\n",
      "\n",
      "2023-09-28 15:40:03.884044, p680, th139982298342464, INFO Abandoning block: [block pool ID: BP-435783800-172.19.0.4-1695890191831 block ID 1073741825_1001] for file /test.txt.\n",
      "2023-09-28 15:40:03.895083, p680, th139982298342464, INFO Excluding invalid datanode: 40d68dbd7a95(172.19.0.3) for block [block pool ID: BP-435783800-172.19.0.4-1695890191831 block ID 1073741825_1001] for file /test.txt\n",
      "2023-09-28 15:40:04.058190, p680, th139982298342464, ERROR Failed to allocate a new empty block for file /test.txt, last block Null, excluded nodes [40d68dbd7a95(172.19.0.3)].\n",
      "NamenodeImpl.cpp: 277: File /test.txt could only be written to 0 of the 1 minReplication nodes. There are 1 datanode(s) running and 1 node(s) are excluded in this operation.\n",
      "\tat org.apache.hadoop.hdfs.server.blockmanagement.BlockManager.chooseTarget4NewBlock(BlockManager.java:2350)\n",
      "\tat org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.chooseTargetForNewBlock(FSDirWriteFileOp.java:294)\n",
      "\tat org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getAdditionalBlock(FSNamesystem.java:2989)\n",
      "\tat org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.addBlock(NameNodeRpcServer.java:912)\n",
      "\tat org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.addBlock(ClientNamenodeProtocolServerSideTranslatorPB.java:595)\n",
      "\tat org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)\n",
      "\tat org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:621)\n",
      "\tat org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:589)\n",
      "\tat org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:573)\n",
      "\tat org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1227)\n",
      "\tat org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:1094)\n",
      "\tat org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:1017)\n",
      "\tat java.security.AccessController.doPrivileged(Native Method)\n",
      "\tat javax.security.auth.Subject.doAs(Subject.java:422)\n",
      "\tat org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1899)\n",
      "\tat org.apache.hadoop.ipc.Server$Handler.run(Server.java:3048)\n",
      "\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tffi_closure_alloc\n",
      "\t@\tdlfree\n",
      "\t@\tdlmmap.constprop.0\n",
      "\t@\tu_set\n",
      "\t@\tUnknown\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tPyEval_EvalCodeEx\n",
      "\t@\tPyEval_EvalCode\n",
      "\t@\tbuiltin_exec\n",
      "\t@\tcfunction_vectorcall_FASTCALL\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tmethod_vectorcall_O\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\tPyObject_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\n",
      "2023-09-28 15:40:04.058311, p680, th139982298342464, ERROR Handle Exception: NamenodeImpl.cpp: 277: File /test.txt could only be written to 0 of the 1 minReplication nodes. There are 1 datanode(s) running and 1 node(s) are excluded in this operation.\n",
      "\tat org.apache.hadoop.hdfs.server.blockmanagement.BlockManager.chooseTarget4NewBlock(BlockManager.java:2350)\n",
      "\tat org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.chooseTargetForNewBlock(FSDirWriteFileOp.java:294)\n",
      "\tat org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getAdditionalBlock(FSNamesystem.java:2989)\n",
      "\tat org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.addBlock(NameNodeRpcServer.java:912)\n",
      "\tat org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.addBlock(ClientNamenodeProtocolServerSideTranslatorPB.java:595)\n",
      "\tat org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)\n",
      "\tat org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:621)\n",
      "\tat org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:589)\n",
      "\tat org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:573)\n",
      "\tat org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1227)\n",
      "\tat org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:1094)\n",
      "\tat org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:1017)\n",
      "\tat java.security.AccessController.doPrivileged(Native Method)\n",
      "\tat javax.security.auth.Subject.doAs(Subject.java:422)\n",
      "\tat org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1899)\n",
      "\tat org.apache.hadoop.ipc.Server$Handler.run(Server.java:3048)\n",
      "\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tffi_closure_alloc\n",
      "\t@\tdlfree\n",
      "\t@\tdlmmap.constprop.0\n",
      "\t@\tu_set\n",
      "\t@\tUnknown\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tPyEval_EvalCodeEx\n",
      "\t@\tPyEval_EvalCode\n",
      "\t@\tbuiltin_exec\n",
      "\t@\tcfunction_vectorcall_FASTCALL\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tmethod_vectorcall_O\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\tPyObject_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    hdfs.put('test.txt','/test.txt')\n",
    "except Exception as e:\n",
    "    print(e)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-09-28 15:47:14.037917, p680, th139982298342464, ERROR cannot setup block reader for Block: [block pool ID: BP-435783800-172.19.0.4-1695890191831 block ID 1073741826_1002] file /test.txt on Datanode: 40d68dbd7a95(172.19.0.3).\n",
      "RemoteBlockReader.cpp: 122: HdfsIOException: RemoteBlockReader: Failed to connect to 40d68dbd7a95(172.19.0.3)\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tffi_closure_alloc\n",
      "\t@\tdlfree\n",
      "\t@\tdlmmap.constprop.0\n",
      "\t@\tu_set\n",
      "\t@\tunpickle\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tPyEval_EvalCodeEx\n",
      "\t@\tPyEval_EvalCode\n",
      "\t@\tbuiltin_exec\n",
      "\t@\tcfunction_vectorcall_FASTCALL\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tmethod_vectorcall_O\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\tPyObject_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\tcontext_run\n",
      "\t@\tcfunction_vectorcall_FASTCALL_KEYWORDS\n",
      "\t@\tPyVectorcall_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "Caused by\n",
      "TcpSocket.cpp: 282: HdfsTimeoutException: Connect to \"172.19.0.3:9866\" timeout\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tffi_closure_alloc\n",
      "\t@\tdlfree\n",
      "\t@\tdlmmap.constprop.0\n",
      "\t@\tu_set\n",
      "\t@\tunpickle\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tPyEval_EvalCodeEx\n",
      "\t@\tPyEval_EvalCode\n",
      "\t@\tbuiltin_exec\n",
      "\t@\tcfunction_vectorcall_FASTCALL\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tmethod_vectorcall_O\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\tPyObject_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\tcontext_run\n",
      "\t@\tcfunction_vectorcall_FASTCALL_KEYWORDS\n",
      "\t@\tPyVectorcall_Call\n",
      "\n",
      "retry another node\n",
      "2023-09-28 15:47:14.187201, p680, th139982298342464, ERROR InputStreamImpl: failed to read Block: [block pool ID: BP-435783800-172.19.0.4-1695890191831 block ID 1073741826_1002] file /test.txt, \n",
      "InputStreamImpl.cpp: 329: HdfsIOException: InputStreamImpl: all nodes have been tried and no valid replica can be read for Block: [block pool ID: BP-435783800-172.19.0.4-1695890191831 block ID 1073741826_1002].\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tffi_closure_alloc\n",
      "\t@\tdlfree\n",
      "\t@\tdlmmap.constprop.0\n",
      "\t@\tu_set\n",
      "\t@\tunpickle\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tPyEval_EvalCodeEx\n",
      "\t@\tPyEval_EvalCode\n",
      "\t@\tbuiltin_exec\n",
      "\t@\tcfunction_vectorcall_FASTCALL\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tmethod_vectorcall_O\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\tPyObject_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\tcontext_run\n",
      "\t@\tcfunction_vectorcall_FASTCALL_KEYWORDS\n",
      "\t@\tPyVectorcall_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "Caused by\n",
      "RemoteBlockReader.cpp: 122: HdfsIOException: RemoteBlockReader: Failed to connect to 40d68dbd7a95(172.19.0.3)\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tffi_closure_alloc\n",
      "\t@\tdlfree\n",
      "\t@\tdlmmap.constprop.0\n",
      "\t@\tu_set\n",
      "\t@\tunpickle\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tPyEval_EvalCodeEx\n",
      "\t@\tPyEval_EvalCode\n",
      "\t@\tbuiltin_exec\n",
      "\t@\tcfunction_vectorcall_FASTCALL\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tmethod_vectorcall_O\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\tPyObject_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\tcontext_run\n",
      "\t@\tcfunction_vectorcall_FASTCALL_KEYWORDS\n",
      "\t@\tPyVectorcall_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "Caused by\n",
      "TcpSocket.cpp: 282: HdfsTimeoutException: Connect to \"172.19.0.3:9866\" timeout\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tffi_closure_alloc\n",
      "\t@\tdlfree\n",
      "\t@\tdlmmap.constprop.0\n",
      "\t@\tu_set\n",
      "\t@\tunpickle\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tPyEval_EvalCodeEx\n",
      "\t@\tPyEval_EvalCode\n",
      "\t@\tbuiltin_exec\n",
      "\t@\tcfunction_vectorcall_FASTCALL\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tmethod_vectorcall_O\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\tPyObject_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\tcontext_run\n",
      "\t@\tcfunction_vectorcall_FASTCALL_KEYWORDS\n",
      "\t@\tPyVectorcall_Call\n",
      ", retry after updating block informations.\n",
      "2023-09-28 15:49:32.271301, p680, th139982298342464, ERROR cannot setup block reader for Block: [block pool ID: BP-435783800-172.19.0.4-1695890191831 block ID 1073741826_1002] file /test.txt on Datanode: 40d68dbd7a95(172.19.0.3).\n",
      "RemoteBlockReader.cpp: 122: HdfsIOException: RemoteBlockReader: Failed to connect to 40d68dbd7a95(172.19.0.3)\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tffi_closure_alloc\n",
      "\t@\tdlfree\n",
      "\t@\tdlmmap.constprop.0\n",
      "\t@\tu_set\n",
      "\t@\tunpickle\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tPyEval_EvalCodeEx\n",
      "\t@\tPyEval_EvalCode\n",
      "\t@\tbuiltin_exec\n",
      "\t@\tcfunction_vectorcall_FASTCALL\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tmethod_vectorcall_O\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\tPyObject_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\tcontext_run\n",
      "\t@\tcfunction_vectorcall_FASTCALL_KEYWORDS\n",
      "\t@\tPyVectorcall_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "Caused by\n",
      "TcpSocket.cpp: 282: HdfsTimeoutException: Connect to \"172.19.0.3:9866\" timeout\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tffi_closure_alloc\n",
      "\t@\tdlfree\n",
      "\t@\tdlmmap.constprop.0\n",
      "\t@\tu_set\n",
      "\t@\tunpickle\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tPyEval_EvalCodeEx\n",
      "\t@\tPyEval_EvalCode\n",
      "\t@\tbuiltin_exec\n",
      "\t@\tcfunction_vectorcall_FASTCALL\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tmethod_vectorcall_O\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\tPyObject_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\tcontext_run\n",
      "\t@\tcfunction_vectorcall_FASTCALL_KEYWORDS\n",
      "\t@\tPyVectorcall_Call\n",
      "\n",
      "retry another node\n",
      "2023-09-28 15:49:32.408364, p680, th139982298342464, ERROR InputStreamImpl: failed to read Block: [block pool ID: BP-435783800-172.19.0.4-1695890191831 block ID 1073741826_1002] file /test.txt, \n",
      "InputStreamImpl.cpp: 329: HdfsIOException: InputStreamImpl: all nodes have been tried and no valid replica can be read for Block: [block pool ID: BP-435783800-172.19.0.4-1695890191831 block ID 1073741826_1002].\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tffi_closure_alloc\n",
      "\t@\tdlfree\n",
      "\t@\tdlmmap.constprop.0\n",
      "\t@\tu_set\n",
      "\t@\tunpickle\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tPyEval_EvalCodeEx\n",
      "\t@\tPyEval_EvalCode\n",
      "\t@\tbuiltin_exec\n",
      "\t@\tcfunction_vectorcall_FASTCALL\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tmethod_vectorcall_O\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\tPyObject_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\tcontext_run\n",
      "\t@\tcfunction_vectorcall_FASTCALL_KEYWORDS\n",
      "\t@\tPyVectorcall_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "Caused by\n",
      "RemoteBlockReader.cpp: 122: HdfsIOException: RemoteBlockReader: Failed to connect to 40d68dbd7a95(172.19.0.3)\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tffi_closure_alloc\n",
      "\t@\tdlfree\n",
      "\t@\tdlmmap.constprop.0\n",
      "\t@\tu_set\n",
      "\t@\tunpickle\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tPyEval_EvalCodeEx\n",
      "\t@\tPyEval_EvalCode\n",
      "\t@\tbuiltin_exec\n",
      "\t@\tcfunction_vectorcall_FASTCALL\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tmethod_vectorcall_O\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\tPyObject_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\tcontext_run\n",
      "\t@\tcfunction_vectorcall_FASTCALL_KEYWORDS\n",
      "\t@\tPyVectorcall_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "Caused by\n",
      "TcpSocket.cpp: 282: HdfsTimeoutException: Connect to \"172.19.0.3:9866\" timeout\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tffi_closure_alloc\n",
      "\t@\tdlfree\n",
      "\t@\tdlmmap.constprop.0\n",
      "\t@\tu_set\n",
      "\t@\tunpickle\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tPyEval_EvalCodeEx\n",
      "\t@\tPyEval_EvalCode\n",
      "\t@\tbuiltin_exec\n",
      "\t@\tcfunction_vectorcall_FASTCALL\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tmethod_vectorcall_O\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\tPyObject_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\tcontext_run\n",
      "\t@\tcfunction_vectorcall_FASTCALL_KEYWORDS\n",
      "\t@\tPyVectorcall_Call\n",
      ", retry after updating block informations.\n",
      "2023-09-28 15:51:50.508712, p680, th139982298342464, ERROR cannot setup block reader for Block: [block pool ID: BP-435783800-172.19.0.4-1695890191831 block ID 1073741826_1002] file /test.txt on Datanode: 40d68dbd7a95(172.19.0.3).\n",
      "RemoteBlockReader.cpp: 122: HdfsIOException: RemoteBlockReader: Failed to connect to 40d68dbd7a95(172.19.0.3)\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tffi_closure_alloc\n",
      "\t@\tdlfree\n",
      "\t@\tdlmmap.constprop.0\n",
      "\t@\tu_set\n",
      "\t@\tunpickle\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tPyEval_EvalCodeEx\n",
      "\t@\tPyEval_EvalCode\n",
      "\t@\tbuiltin_exec\n",
      "\t@\tcfunction_vectorcall_FASTCALL\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tmethod_vectorcall_O\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\tPyObject_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\tcontext_run\n",
      "\t@\tcfunction_vectorcall_FASTCALL_KEYWORDS\n",
      "\t@\tPyVectorcall_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "Caused by\n",
      "TcpSocket.cpp: 282: HdfsTimeoutException: Connect to \"172.19.0.3:9866\" timeout\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tffi_closure_alloc\n",
      "\t@\tdlfree\n",
      "\t@\tdlmmap.constprop.0\n",
      "\t@\tu_set\n",
      "\t@\tunpickle\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tPyEval_EvalCodeEx\n",
      "\t@\tPyEval_EvalCode\n",
      "\t@\tbuiltin_exec\n",
      "\t@\tcfunction_vectorcall_FASTCALL\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tmethod_vectorcall_O\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\tPyObject_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\tcontext_run\n",
      "\t@\tcfunction_vectorcall_FASTCALL_KEYWORDS\n",
      "\t@\tPyVectorcall_Call\n",
      "\n",
      "retry another node\n",
      "2023-09-28 15:51:50.603691, p680, th139982298342464, ERROR InputStreamImpl: failed to read Block: [block pool ID: BP-435783800-172.19.0.4-1695890191831 block ID 1073741826_1002] file /test.txt, \n",
      "InputStreamImpl.cpp: 329: HdfsIOException: InputStreamImpl: all nodes have been tried and no valid replica can be read for Block: [block pool ID: BP-435783800-172.19.0.4-1695890191831 block ID 1073741826_1002].\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tffi_closure_alloc\n",
      "\t@\tdlfree\n",
      "\t@\tdlmmap.constprop.0\n",
      "\t@\tu_set\n",
      "\t@\tunpickle\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tPyEval_EvalCodeEx\n",
      "\t@\tPyEval_EvalCode\n",
      "\t@\tbuiltin_exec\n",
      "\t@\tcfunction_vectorcall_FASTCALL\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tmethod_vectorcall_O\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\tPyObject_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\tcontext_run\n",
      "\t@\tcfunction_vectorcall_FASTCALL_KEYWORDS\n",
      "\t@\tPyVectorcall_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "Caused by\n",
      "RemoteBlockReader.cpp: 122: HdfsIOException: RemoteBlockReader: Failed to connect to 40d68dbd7a95(172.19.0.3)\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tffi_closure_alloc\n",
      "\t@\tdlfree\n",
      "\t@\tdlmmap.constprop.0\n",
      "\t@\tu_set\n",
      "\t@\tunpickle\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tPyEval_EvalCodeEx\n",
      "\t@\tPyEval_EvalCode\n",
      "\t@\tbuiltin_exec\n",
      "\t@\tcfunction_vectorcall_FASTCALL\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tmethod_vectorcall_O\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\tPyObject_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\tcontext_run\n",
      "\t@\tcfunction_vectorcall_FASTCALL_KEYWORDS\n",
      "\t@\tPyVectorcall_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "Caused by\n",
      "TcpSocket.cpp: 282: HdfsTimeoutException: Connect to \"172.19.0.3:9866\" timeout\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tffi_closure_alloc\n",
      "\t@\tdlfree\n",
      "\t@\tdlmmap.constprop.0\n",
      "\t@\tu_set\n",
      "\t@\tunpickle\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tPyEval_EvalCodeEx\n",
      "\t@\tPyEval_EvalCode\n",
      "\t@\tbuiltin_exec\n",
      "\t@\tcfunction_vectorcall_FASTCALL\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tmethod_vectorcall_O\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\tPyObject_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\tcontext_run\n",
      "\t@\tcfunction_vectorcall_FASTCALL_KEYWORDS\n",
      "\t@\tPyVectorcall_Call\n",
      ", retry after updating block informations.\n"
     ]
    }
   ],
   "source": [
    "with hdfs.open(\"/test.txt\", \"rb\") as file:\n",
    "    data = file.read(1000)\n",
    "\n",
    "data"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "hdfs",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.18"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
