{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Test interact with CLickhouse and HDFS"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "from clickhouse_driver import Client\n",
    "import pandas as pd\n",
    "import os\n",
    "from dotenv import load_dotenv"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Clickhouse cloud"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[('INFORMATION_SCHEMA',),\n",
       " ('default',),\n",
       " ('information_schema',),\n",
       " ('mydb',),\n",
       " ('system',)]"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# load env\n",
    "load_dotenv()\n",
    "\n",
    "cloud=os.getenv(\"HOST\")\n",
    "user=os.getenv(\"USERNAME\")\n",
    "password=os.getenv(\"PASS\")\n",
    "port=9440\n",
    "\n",
    "# Connect to database\n",
    "conn = Client(host=cloud, port=port, user=user, password=password, secure='y',verify=False)\n",
    "conn.execute(\"show databases\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [],
   "source": [
    "df = pd.DataFrame([\n",
    "    {'year': 1994, 'first_name': 'Vova'},\n",
    "    {'year': 1995, 'first_name': 'Anja'},\n",
    "    {'year': 1996, 'first_name': 'Vasja'},\n",
    "    {'year': 1997, 'first_name': 'Petja'},\n",
    "    {'year': 2000, 'first_name': 'Petja'},\n",
    "    {'year': 2131, 'first_name': 'Petja'},\n",
    "])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Create database mydb\n",
      "done...\n",
      "Created table mydb.test\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    print('Create database mydb')\n",
    "    conn.execute('create database if not exists mydb')\n",
    "    print('done...')\n",
    "    conn.execute('''\n",
    "    create table if not exists mydb.test(\n",
    "        year Int,\n",
    "        first_name String\n",
    "    ) engine = Memory\n",
    "    ''')\n",
    "    print('Created table mydb.test')\n",
    "except Exception as e:\n",
    "    print(e)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "done pussing 6 into test table\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    row = conn.execute(\"insert into mydb.test values\", df.to_dict('records'))\n",
    "    print(f'done pussing {row} into test table')\n",
    "except Exception as e:\n",
    "    print(e)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[(1994, 'Vova'),\n",
       " (1995, 'Anja'),\n",
       " (1996, 'Vasja'),\n",
       " (1997, 'Petja'),\n",
       " (2000, 'Petja'),\n",
       " (2131, 'Petja')]"
      ]
     },
     "execution_count": 16,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "conn.execute('select * from mydb.test')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Local"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "conn = Client('localhost')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[('INFORMATION_SCHEMA',),\n",
       " ('default',),\n",
       " ('information_schema',),\n",
       " ('system',),\n",
       " ('testdb',)]"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "conn.execute(\"show databases\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "create table ny_taxi_data\n",
      "Done...\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    print(\"create table ny_taxi_data\")\n",
    "    conn.execute(\"\"\"\n",
    "    CREATE TABLE IF NOT EXISTS yellow_taxi_data (\n",
    "\t\"VendorID\" BIGINT, \n",
    "\ttpep_pickup_datetime TIMESTAMP, \n",
    "\ttpep_dropoff_datetime TIMESTAMP, \n",
    "\tpassenger_count FLOAT(53), \n",
    "\ttrip_distance FLOAT(53), \n",
    "\t\"RatecodeID\" FLOAT(53), \n",
    "\tstore_and_fwd_flag TEXT, \n",
    "\t\"PULocationID\" BIGINT, \n",
    "\t\"DOLocationID\" BIGINT, \n",
    "\tpayment_type BIGINT, \n",
    "\tfare_amount FLOAT(53), \n",
    "\textra FLOAT(53), \n",
    "\tmta_tax FLOAT(53), \n",
    "\ttip_amount FLOAT(53), \n",
    "\ttolls_amount FLOAT(53), \n",
    "\timprovement_surcharge FLOAT(53), \n",
    "\ttotal_amount FLOAT(53), \n",
    "\tcongestion_surcharge FLOAT(53), \n",
    "\tairport_fee FLOAT(53)\n",
    ") ENGINE = Memory\n",
    "\"\"\")\n",
    "    print('Done...')\n",
    "except Exception as e:\n",
    "    print(e)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## HDFS"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[]"
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "from hdfs3 import HDFileSystem\n",
    "port = 8020\n",
    "hdfs = HDFileSystem('localhost', port)\n",
    "hdfs.ls('/')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-10-07 19:30:49.274231, p23059, th140164915422272, ERROR Failed to setup the pipeline for new block [block pool ID: BP-1713148376-172.24.0.4-1696679760667 block ID 1073741828_1004] file /hello/a.txt.\n",
      "Pipeline.cpp: 700: HdfsIOException: Cannot create block output stream for block [block pool ID: BP-1713148376-172.24.0.4-1696679760667 block ID 1073741828_1004], recovery flag: false, with last generate stamp 0.\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tffi_closure_alloc\n",
      "\t@\tdlfree\n",
      "\t@\tdlmmap.constprop.0\n",
      "\t@\tu_set\n",
      "\t@\tUnknown\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tPyEval_EvalCodeEx\n",
      "\t@\tPyEval_EvalCode\n",
      "\t@\tbuiltin_exec\n",
      "\t@\tcfunction_vectorcall_FASTCALL\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tmethod_vectorcall_O\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\tPyObject_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\tcontext_run\n",
      "Caused by\n",
      "TcpSocket.cpp: 282: HdfsTimeoutException: Connect to \"172.24.0.5:9866\" timeout\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tffi_closure_alloc\n",
      "\t@\tdlfree\n",
      "\t@\tdlmmap.constprop.0\n",
      "\t@\tu_set\n",
      "\t@\tUnknown\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tPyEval_EvalCodeEx\n",
      "\t@\tPyEval_EvalCode\n",
      "\t@\tbuiltin_exec\n",
      "\t@\tcfunction_vectorcall_FASTCALL\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tmethod_vectorcall_O\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\tPyObject_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tUnknown\n",
      "\n",
      "2023-10-07 19:30:49.274329, p23059, th140164915422272, INFO Abandoning block: [block pool ID: BP-1713148376-172.24.0.4-1696679760667 block ID 1073741828_1004] for file /hello/a.txt.\n",
      "2023-10-07 19:30:49.277708, p23059, th140164915422272, INFO Excluding invalid datanode: datanode(172.24.0.5) for block [block pool ID: BP-1713148376-172.24.0.4-1696679760667 block ID 1073741828_1004] for file /hello/a.txt\n",
      "2023-10-07 19:30:49.346766, p23059, th140164915422272, ERROR Failed to allocate a new empty block for file /hello/a.txt, last block Null, excluded nodes [datanode(172.24.0.5)].\n",
      "NamenodeImpl.cpp: 277: File /hello/a.txt could only be written to 0 of the 1 minReplication nodes. There are 1 datanode(s) running and 1 node(s) are excluded in this operation.\n",
      "\tat org.apache.hadoop.hdfs.server.blockmanagement.BlockManager.chooseTarget4NewBlock(BlockManager.java:2350)\n",
      "\tat org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.chooseTargetForNewBlock(FSDirWriteFileOp.java:294)\n",
      "\tat org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getAdditionalBlock(FSNamesystem.java:2989)\n",
      "\tat org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.addBlock(NameNodeRpcServer.java:912)\n",
      "\tat org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.addBlock(ClientNamenodeProtocolServerSideTranslatorPB.java:595)\n",
      "\tat org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)\n",
      "\tat org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:621)\n",
      "\tat org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:589)\n",
      "\tat org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:573)\n",
      "\tat org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1227)\n",
      "\tat org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:1094)\n",
      "\tat org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:1017)\n",
      "\tat java.security.AccessController.doPrivileged(Native Method)\n",
      "\tat javax.security.auth.Subject.doAs(Subject.java:422)\n",
      "\tat org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1899)\n",
      "\tat org.apache.hadoop.ipc.Server$Handler.run(Server.java:3048)\n",
      "\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tffi_closure_alloc\n",
      "\t@\tdlfree\n",
      "\t@\tdlmmap.constprop.0\n",
      "\t@\tu_set\n",
      "\t@\tUnknown\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tPyEval_EvalCodeEx\n",
      "\t@\tPyEval_EvalCode\n",
      "\t@\tbuiltin_exec\n",
      "\t@\tcfunction_vectorcall_FASTCALL\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tmethod_vectorcall_O\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\tPyObject_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\n",
      "2023-10-07 19:30:49.346850, p23059, th140164915422272, ERROR Handle Exception: NamenodeImpl.cpp: 277: File /hello/a.txt could only be written to 0 of the 1 minReplication nodes. There are 1 datanode(s) running and 1 node(s) are excluded in this operation.\n",
      "\tat org.apache.hadoop.hdfs.server.blockmanagement.BlockManager.chooseTarget4NewBlock(BlockManager.java:2350)\n",
      "\tat org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.chooseTargetForNewBlock(FSDirWriteFileOp.java:294)\n",
      "\tat org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getAdditionalBlock(FSNamesystem.java:2989)\n",
      "\tat org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.addBlock(NameNodeRpcServer.java:912)\n",
      "\tat org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.addBlock(ClientNamenodeProtocolServerSideTranslatorPB.java:595)\n",
      "\tat org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)\n",
      "\tat org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:621)\n",
      "\tat org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:589)\n",
      "\tat org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:573)\n",
      "\tat org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1227)\n",
      "\tat org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:1094)\n",
      "\tat org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:1017)\n",
      "\tat java.security.AccessController.doPrivileged(Native Method)\n",
      "\tat javax.security.auth.Subject.doAs(Subject.java:422)\n",
      "\tat org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1899)\n",
      "\tat org.apache.hadoop.ipc.Server$Handler.run(Server.java:3048)\n",
      "\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tffi_closure_alloc\n",
      "\t@\tdlfree\n",
      "\t@\tdlmmap.constprop.0\n",
      "\t@\tu_set\n",
      "\t@\tUnknown\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tPyEval_EvalCodeEx\n",
      "\t@\tPyEval_EvalCode\n",
      "\t@\tbuiltin_exec\n",
      "\t@\tcfunction_vectorcall_FASTCALL\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tmethod_vectorcall_O\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\tPyObject_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\n"
     ]
    }
   ],
   "source": [
    "hdfs.put(\"requirements.txt\", \"/hello/a.txt\", replication=1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "ename": "KeyboardInterrupt",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
      "\u001b[1;32m/home/phonghuynh/Desktop/Tech/DE_bootcamp/week_2/clickhouse-connect.ipynb Cell 15\u001b[0m line \u001b[0;36m4\n\u001b[1;32m      <a href='vscode-notebook-cell://wsl%2Bubuntu-22.04/home/phonghuynh/Desktop/Tech/DE_bootcamp/week_2/clickhouse-connect.ipynb#X20sdnNjb2RlLXJlbW90ZQ%3D%3D?line=0'>1</a>\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mhdfs\u001b[39;00m \u001b[39mimport\u001b[39;00m InsecureClient\n\u001b[1;32m      <a href='vscode-notebook-cell://wsl%2Bubuntu-22.04/home/phonghuynh/Desktop/Tech/DE_bootcamp/week_2/clickhouse-connect.ipynb#X20sdnNjb2RlLXJlbW90ZQ%3D%3D?line=1'>2</a>\u001b[0m client \u001b[39m=\u001b[39m InsecureClient(\u001b[39m'\u001b[39m\u001b[39mhttp://localhost:9000\u001b[39m\u001b[39m'\u001b[39m, user\u001b[39m=\u001b[39m\u001b[39m'\u001b[39m\u001b[39mann\u001b[39m\u001b[39m'\u001b[39m)\n\u001b[0;32m----> <a href='vscode-notebook-cell://wsl%2Bubuntu-22.04/home/phonghuynh/Desktop/Tech/DE_bootcamp/week_2/clickhouse-connect.ipynb#X20sdnNjb2RlLXJlbW90ZQ%3D%3D?line=3'>4</a>\u001b[0m \u001b[39mwith\u001b[39;00m client\u001b[39m.\u001b[39mread(\u001b[39m'\u001b[39m\u001b[39m/test.txt\u001b[39m\u001b[39m'\u001b[39m) \u001b[39mas\u001b[39;00m file:\n\u001b[1;32m      <a href='vscode-notebook-cell://wsl%2Bubuntu-22.04/home/phonghuynh/Desktop/Tech/DE_bootcamp/week_2/clickhouse-connect.ipynb#X20sdnNjb2RlLXJlbW90ZQ%3D%3D?line=4'>5</a>\u001b[0m     \u001b[39mprint\u001b[39m(file\u001b[39m.\u001b[39mread())\n",
      "File \u001b[0;32m~/miniconda3/envs/hdfs/lib/python3.8/contextlib.py:113\u001b[0m, in \u001b[0;36m_GeneratorContextManager.__enter__\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    111\u001b[0m \u001b[39mdel\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39margs, \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mkwds, \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mfunc\n\u001b[1;32m    112\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m--> 113\u001b[0m     \u001b[39mreturn\u001b[39;00m \u001b[39mnext\u001b[39;49m(\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mgen)\n\u001b[1;32m    114\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mStopIteration\u001b[39;00m:\n\u001b[1;32m    115\u001b[0m     \u001b[39mraise\u001b[39;00m \u001b[39mRuntimeError\u001b[39;00m(\u001b[39m\"\u001b[39m\u001b[39mgenerator didn\u001b[39m\u001b[39m'\u001b[39m\u001b[39mt yield\u001b[39m\u001b[39m\"\u001b[39m) \u001b[39mfrom\u001b[39;00m \u001b[39mNone\u001b[39;00m\n",
      "File \u001b[0;32m~/miniconda3/envs/hdfs/lib/python3.8/site-packages/hdfs/client.py:725\u001b[0m, in \u001b[0;36mClient.read\u001b[0;34m(self, hdfs_path, offset, length, buffer_size, encoding, chunk_size, delimiter, progress)\u001b[0m\n\u001b[1;32m    723\u001b[0m     \u001b[39mraise\u001b[39;00m \u001b[39mValueError\u001b[39;00m(\u001b[39m'\u001b[39m\u001b[39mDelimiter splitting incompatible with chunk size.\u001b[39m\u001b[39m'\u001b[39m)\n\u001b[1;32m    724\u001b[0m _logger\u001b[39m.\u001b[39minfo(\u001b[39m'\u001b[39m\u001b[39mReading file \u001b[39m\u001b[39m%r\u001b[39;00m\u001b[39m.\u001b[39m\u001b[39m'\u001b[39m, hdfs_path)\n\u001b[0;32m--> 725\u001b[0m res \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_open(\n\u001b[1;32m    726\u001b[0m   hdfs_path,\n\u001b[1;32m    727\u001b[0m   offset\u001b[39m=\u001b[39;49moffset,\n\u001b[1;32m    728\u001b[0m   length\u001b[39m=\u001b[39;49mlength,\n\u001b[1;32m    729\u001b[0m   buffersize\u001b[39m=\u001b[39;49mbuffer_size,\n\u001b[1;32m    730\u001b[0m )\n\u001b[1;32m    731\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m    732\u001b[0m   \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m chunk_size \u001b[39mand\u001b[39;00m \u001b[39mnot\u001b[39;00m delimiter:\n",
      "File \u001b[0;32m~/miniconda3/envs/hdfs/lib/python3.8/site-packages/hdfs/client.py:102\u001b[0m, in \u001b[0;36m_Request.to_method.<locals>.api_handler\u001b[0;34m(client, hdfs_path, data, strict, **params)\u001b[0m\n\u001b[1;32m    100\u001b[0m err \u001b[39m=\u001b[39m \u001b[39mNone\u001b[39;00m\n\u001b[1;32m    101\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m--> 102\u001b[0m   res \u001b[39m=\u001b[39m client\u001b[39m.\u001b[39;49m_request(\n\u001b[1;32m    103\u001b[0m     method\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mmethod,\n\u001b[1;32m    104\u001b[0m     url\u001b[39m=\u001b[39;49murl,\n\u001b[1;32m    105\u001b[0m     data\u001b[39m=\u001b[39;49mdata,\n\u001b[1;32m    106\u001b[0m     params\u001b[39m=\u001b[39;49mparams,\n\u001b[1;32m    107\u001b[0m     \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mkwargs\n\u001b[1;32m    108\u001b[0m   )\n\u001b[1;32m    109\u001b[0m \u001b[39mexcept\u001b[39;00m (rq\u001b[39m.\u001b[39mexceptions\u001b[39m.\u001b[39mReadTimeout, rq\u001b[39m.\u001b[39mexceptions\u001b[39m.\u001b[39mConnectTimeout,\n\u001b[1;32m    110\u001b[0m         rq\u001b[39m.\u001b[39mexceptions\u001b[39m.\u001b[39mConnectionError) \u001b[39mas\u001b[39;00m retriable_err:\n\u001b[1;32m    111\u001b[0m   err \u001b[39m=\u001b[39m retriable_err \u001b[39m# Retry.\u001b[39;00m\n",
      "File \u001b[0;32m~/miniconda3/envs/hdfs/lib/python3.8/site-packages/hdfs/client.py:209\u001b[0m, in \u001b[0;36mClient._request\u001b[0;34m(self, method, url, **kwargs)\u001b[0m\n\u001b[1;32m    199\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39m_request\u001b[39m(\u001b[39mself\u001b[39m, method, url, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs):\n\u001b[1;32m    200\u001b[0m \u001b[39m  \u001b[39m\u001b[39mr\u001b[39m\u001b[39m\"\"\"Send request to WebHDFS API.\u001b[39;00m\n\u001b[1;32m    201\u001b[0m \n\u001b[1;32m    202\u001b[0m \u001b[39m  :param method: HTTP verb.\u001b[39;00m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    207\u001b[0m \n\u001b[1;32m    208\u001b[0m \u001b[39m  \"\"\"\u001b[39;00m\n\u001b[0;32m--> 209\u001b[0m   \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_session\u001b[39m.\u001b[39;49mrequest(\n\u001b[1;32m    210\u001b[0m     method\u001b[39m=\u001b[39;49mmethod,\n\u001b[1;32m    211\u001b[0m     url\u001b[39m=\u001b[39;49murl,\n\u001b[1;32m    212\u001b[0m     timeout\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_timeout,\n\u001b[1;32m    213\u001b[0m     headers\u001b[39m=\u001b[39;49m{\u001b[39m'\u001b[39;49m\u001b[39mcontent-type\u001b[39;49m\u001b[39m'\u001b[39;49m: \u001b[39m'\u001b[39;49m\u001b[39mapplication/octet-stream\u001b[39;49m\u001b[39m'\u001b[39;49m}, \u001b[39m# For HttpFS.\u001b[39;49;00m\n\u001b[1;32m    214\u001b[0m     \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mkwargs\n\u001b[1;32m    215\u001b[0m   )\n",
      "File \u001b[0;32m~/miniconda3/envs/hdfs/lib/python3.8/site-packages/requests/sessions.py:589\u001b[0m, in \u001b[0;36mSession.request\u001b[0;34m(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)\u001b[0m\n\u001b[1;32m    584\u001b[0m send_kwargs \u001b[39m=\u001b[39m {\n\u001b[1;32m    585\u001b[0m     \u001b[39m\"\u001b[39m\u001b[39mtimeout\u001b[39m\u001b[39m\"\u001b[39m: timeout,\n\u001b[1;32m    586\u001b[0m     \u001b[39m\"\u001b[39m\u001b[39mallow_redirects\u001b[39m\u001b[39m\"\u001b[39m: allow_redirects,\n\u001b[1;32m    587\u001b[0m }\n\u001b[1;32m    588\u001b[0m send_kwargs\u001b[39m.\u001b[39mupdate(settings)\n\u001b[0;32m--> 589\u001b[0m resp \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49msend(prep, \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49msend_kwargs)\n\u001b[1;32m    591\u001b[0m \u001b[39mreturn\u001b[39;00m resp\n",
      "File \u001b[0;32m~/miniconda3/envs/hdfs/lib/python3.8/site-packages/requests/sessions.py:703\u001b[0m, in \u001b[0;36mSession.send\u001b[0;34m(self, request, **kwargs)\u001b[0m\n\u001b[1;32m    700\u001b[0m start \u001b[39m=\u001b[39m preferred_clock()\n\u001b[1;32m    702\u001b[0m \u001b[39m# Send the request\u001b[39;00m\n\u001b[0;32m--> 703\u001b[0m r \u001b[39m=\u001b[39m adapter\u001b[39m.\u001b[39;49msend(request, \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mkwargs)\n\u001b[1;32m    705\u001b[0m \u001b[39m# Total elapsed time of the request (approximately)\u001b[39;00m\n\u001b[1;32m    706\u001b[0m elapsed \u001b[39m=\u001b[39m preferred_clock() \u001b[39m-\u001b[39m start\n",
      "File \u001b[0;32m~/miniconda3/envs/hdfs/lib/python3.8/site-packages/requests/adapters.py:486\u001b[0m, in \u001b[0;36mHTTPAdapter.send\u001b[0;34m(self, request, stream, timeout, verify, cert, proxies)\u001b[0m\n\u001b[1;32m    483\u001b[0m     timeout \u001b[39m=\u001b[39m TimeoutSauce(connect\u001b[39m=\u001b[39mtimeout, read\u001b[39m=\u001b[39mtimeout)\n\u001b[1;32m    485\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m--> 486\u001b[0m     resp \u001b[39m=\u001b[39m conn\u001b[39m.\u001b[39;49murlopen(\n\u001b[1;32m    487\u001b[0m         method\u001b[39m=\u001b[39;49mrequest\u001b[39m.\u001b[39;49mmethod,\n\u001b[1;32m    488\u001b[0m         url\u001b[39m=\u001b[39;49murl,\n\u001b[1;32m    489\u001b[0m         body\u001b[39m=\u001b[39;49mrequest\u001b[39m.\u001b[39;49mbody,\n\u001b[1;32m    490\u001b[0m         headers\u001b[39m=\u001b[39;49mrequest\u001b[39m.\u001b[39;49mheaders,\n\u001b[1;32m    491\u001b[0m         redirect\u001b[39m=\u001b[39;49m\u001b[39mFalse\u001b[39;49;00m,\n\u001b[1;32m    492\u001b[0m         assert_same_host\u001b[39m=\u001b[39;49m\u001b[39mFalse\u001b[39;49;00m,\n\u001b[1;32m    493\u001b[0m         preload_content\u001b[39m=\u001b[39;49m\u001b[39mFalse\u001b[39;49;00m,\n\u001b[1;32m    494\u001b[0m         decode_content\u001b[39m=\u001b[39;49m\u001b[39mFalse\u001b[39;49;00m,\n\u001b[1;32m    495\u001b[0m         retries\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mmax_retries,\n\u001b[1;32m    496\u001b[0m         timeout\u001b[39m=\u001b[39;49mtimeout,\n\u001b[1;32m    497\u001b[0m         chunked\u001b[39m=\u001b[39;49mchunked,\n\u001b[1;32m    498\u001b[0m     )\n\u001b[1;32m    500\u001b[0m \u001b[39mexcept\u001b[39;00m (ProtocolError, \u001b[39mOSError\u001b[39;00m) \u001b[39mas\u001b[39;00m err:\n\u001b[1;32m    501\u001b[0m     \u001b[39mraise\u001b[39;00m \u001b[39mConnectionError\u001b[39;00m(err, request\u001b[39m=\u001b[39mrequest)\n",
      "File \u001b[0;32m~/miniconda3/envs/hdfs/lib/python3.8/site-packages/urllib3/connectionpool.py:714\u001b[0m, in \u001b[0;36mHTTPConnectionPool.urlopen\u001b[0;34m(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)\u001b[0m\n\u001b[1;32m    711\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_prepare_proxy(conn)\n\u001b[1;32m    713\u001b[0m \u001b[39m# Make the request on the httplib connection object.\u001b[39;00m\n\u001b[0;32m--> 714\u001b[0m httplib_response \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_make_request(\n\u001b[1;32m    715\u001b[0m     conn,\n\u001b[1;32m    716\u001b[0m     method,\n\u001b[1;32m    717\u001b[0m     url,\n\u001b[1;32m    718\u001b[0m     timeout\u001b[39m=\u001b[39;49mtimeout_obj,\n\u001b[1;32m    719\u001b[0m     body\u001b[39m=\u001b[39;49mbody,\n\u001b[1;32m    720\u001b[0m     headers\u001b[39m=\u001b[39;49mheaders,\n\u001b[1;32m    721\u001b[0m     chunked\u001b[39m=\u001b[39;49mchunked,\n\u001b[1;32m    722\u001b[0m )\n\u001b[1;32m    724\u001b[0m \u001b[39m# If we're going to release the connection in ``finally:``, then\u001b[39;00m\n\u001b[1;32m    725\u001b[0m \u001b[39m# the response doesn't need to know about the connection. Otherwise\u001b[39;00m\n\u001b[1;32m    726\u001b[0m \u001b[39m# it will also try to release it and we'll have a double-release\u001b[39;00m\n\u001b[1;32m    727\u001b[0m \u001b[39m# mess.\u001b[39;00m\n\u001b[1;32m    728\u001b[0m response_conn \u001b[39m=\u001b[39m conn \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m release_conn \u001b[39melse\u001b[39;00m \u001b[39mNone\u001b[39;00m\n",
      "File \u001b[0;32m~/miniconda3/envs/hdfs/lib/python3.8/site-packages/urllib3/connectionpool.py:466\u001b[0m, in \u001b[0;36mHTTPConnectionPool._make_request\u001b[0;34m(self, conn, method, url, timeout, chunked, **httplib_request_kw)\u001b[0m\n\u001b[1;32m    461\u001b[0m             httplib_response \u001b[39m=\u001b[39m conn\u001b[39m.\u001b[39mgetresponse()\n\u001b[1;32m    462\u001b[0m         \u001b[39mexcept\u001b[39;00m \u001b[39mBaseException\u001b[39;00m \u001b[39mas\u001b[39;00m e:\n\u001b[1;32m    463\u001b[0m             \u001b[39m# Remove the TypeError from the exception chain in\u001b[39;00m\n\u001b[1;32m    464\u001b[0m             \u001b[39m# Python 3 (including for exceptions like SystemExit).\u001b[39;00m\n\u001b[1;32m    465\u001b[0m             \u001b[39m# Otherwise it looks like a bug in the code.\u001b[39;00m\n\u001b[0;32m--> 466\u001b[0m             six\u001b[39m.\u001b[39;49mraise_from(e, \u001b[39mNone\u001b[39;49;00m)\n\u001b[1;32m    467\u001b[0m \u001b[39mexcept\u001b[39;00m (SocketTimeout, BaseSSLError, SocketError) \u001b[39mas\u001b[39;00m e:\n\u001b[1;32m    468\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_raise_timeout(err\u001b[39m=\u001b[39me, url\u001b[39m=\u001b[39murl, timeout_value\u001b[39m=\u001b[39mread_timeout)\n",
      "File \u001b[0;32m<string>:3\u001b[0m, in \u001b[0;36mraise_from\u001b[0;34m(value, from_value)\u001b[0m\n",
      "File \u001b[0;32m~/miniconda3/envs/hdfs/lib/python3.8/site-packages/urllib3/connectionpool.py:461\u001b[0m, in \u001b[0;36mHTTPConnectionPool._make_request\u001b[0;34m(self, conn, method, url, timeout, chunked, **httplib_request_kw)\u001b[0m\n\u001b[1;32m    458\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mTypeError\u001b[39;00m:\n\u001b[1;32m    459\u001b[0m     \u001b[39m# Python 3\u001b[39;00m\n\u001b[1;32m    460\u001b[0m     \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m--> 461\u001b[0m         httplib_response \u001b[39m=\u001b[39m conn\u001b[39m.\u001b[39;49mgetresponse()\n\u001b[1;32m    462\u001b[0m     \u001b[39mexcept\u001b[39;00m \u001b[39mBaseException\u001b[39;00m \u001b[39mas\u001b[39;00m e:\n\u001b[1;32m    463\u001b[0m         \u001b[39m# Remove the TypeError from the exception chain in\u001b[39;00m\n\u001b[1;32m    464\u001b[0m         \u001b[39m# Python 3 (including for exceptions like SystemExit).\u001b[39;00m\n\u001b[1;32m    465\u001b[0m         \u001b[39m# Otherwise it looks like a bug in the code.\u001b[39;00m\n\u001b[1;32m    466\u001b[0m         six\u001b[39m.\u001b[39mraise_from(e, \u001b[39mNone\u001b[39;00m)\n",
      "File \u001b[0;32m~/miniconda3/envs/hdfs/lib/python3.8/http/client.py:1348\u001b[0m, in \u001b[0;36mHTTPConnection.getresponse\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   1346\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m   1347\u001b[0m     \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m-> 1348\u001b[0m         response\u001b[39m.\u001b[39;49mbegin()\n\u001b[1;32m   1349\u001b[0m     \u001b[39mexcept\u001b[39;00m \u001b[39mConnectionError\u001b[39;00m:\n\u001b[1;32m   1350\u001b[0m         \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mclose()\n",
      "File \u001b[0;32m~/miniconda3/envs/hdfs/lib/python3.8/http/client.py:316\u001b[0m, in \u001b[0;36mHTTPResponse.begin\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    314\u001b[0m \u001b[39m# read until we get a non-100 response\u001b[39;00m\n\u001b[1;32m    315\u001b[0m \u001b[39mwhile\u001b[39;00m \u001b[39mTrue\u001b[39;00m:\n\u001b[0;32m--> 316\u001b[0m     version, status, reason \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_read_status()\n\u001b[1;32m    317\u001b[0m     \u001b[39mif\u001b[39;00m status \u001b[39m!=\u001b[39m CONTINUE:\n\u001b[1;32m    318\u001b[0m         \u001b[39mbreak\u001b[39;00m\n",
      "File \u001b[0;32m~/miniconda3/envs/hdfs/lib/python3.8/http/client.py:277\u001b[0m, in \u001b[0;36mHTTPResponse._read_status\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    276\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39m_read_status\u001b[39m(\u001b[39mself\u001b[39m):\n\u001b[0;32m--> 277\u001b[0m     line \u001b[39m=\u001b[39m \u001b[39mstr\u001b[39m(\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mfp\u001b[39m.\u001b[39;49mreadline(_MAXLINE \u001b[39m+\u001b[39;49m \u001b[39m1\u001b[39;49m), \u001b[39m\"\u001b[39m\u001b[39miso-8859-1\u001b[39m\u001b[39m\"\u001b[39m)\n\u001b[1;32m    278\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mlen\u001b[39m(line) \u001b[39m>\u001b[39m _MAXLINE:\n\u001b[1;32m    279\u001b[0m         \u001b[39mraise\u001b[39;00m LineTooLong(\u001b[39m\"\u001b[39m\u001b[39mstatus line\u001b[39m\u001b[39m\"\u001b[39m)\n",
      "File \u001b[0;32m~/miniconda3/envs/hdfs/lib/python3.8/socket.py:669\u001b[0m, in \u001b[0;36mSocketIO.readinto\u001b[0;34m(self, b)\u001b[0m\n\u001b[1;32m    667\u001b[0m \u001b[39mwhile\u001b[39;00m \u001b[39mTrue\u001b[39;00m:\n\u001b[1;32m    668\u001b[0m     \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m--> 669\u001b[0m         \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_sock\u001b[39m.\u001b[39;49mrecv_into(b)\n\u001b[1;32m    670\u001b[0m     \u001b[39mexcept\u001b[39;00m timeout:\n\u001b[1;32m    671\u001b[0m         \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_timeout_occurred \u001b[39m=\u001b[39m \u001b[39mTrue\u001b[39;00m\n",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m: "
     ]
    }
   ],
   "source": [
    "from hdfs import InsecureClient\n",
    "client = InsecureClient('http://localhost:9000', user='ann')\n",
    "\n",
    "with client.read('/test.txt') as file:\n",
    "    print(file.read())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "{'capacity': 1081101176832, 'used': 24576, 'percent-free': 99.99999772676226}"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "hdfs.df()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "hdfs.mkdir('hello')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "with hdfs.open(\"/test.txt\") as file:\n",
    "    print(file.read())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-10-02 16:29:06.415154, p3881, th140296688829504, WARNING the number of nodes in pipeline is 1 [datanode(172.21.0.2)], is less than the expected number of replica 3 for block [block pool ID: BP-559880233-172.21.0.5-1696238773587 block ID 1073741825_1001] file /test.txt\n",
      "2023-10-02 16:30:16.387202, p3881, th140296330925632, INFO RPC channel to \"localhost:8020\" got no response or idle for 10000 milliseconds, sending ping.\n",
      "2023-10-02 16:31:17.900974, p3881, th140296688829504, ERROR Failed to setup the pipeline for new block [block pool ID: BP-559880233-172.21.0.5-1696238773587 block ID 1073741825_1001] file /test.txt.\n",
      "Pipeline.cpp: 700: HdfsIOException: Cannot create block output stream for block [block pool ID: BP-559880233-172.21.0.5-1696238773587 block ID 1073741825_1001], recovery flag: false, with last generate stamp 0.\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tffi_closure_alloc\n",
      "\t@\tdlfree\n",
      "\t@\tdlmmap.constprop.0\n",
      "\t@\tu_set\n",
      "\t@\tUnknown\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tPyEval_EvalCodeEx\n",
      "\t@\tPyEval_EvalCode\n",
      "\t@\tbuiltin_exec\n",
      "\t@\tcfunction_vectorcall_FASTCALL\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tmethod_vectorcall_O\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\tPyObject_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\tcontext_run\n",
      "Caused by\n",
      "TcpSocket.cpp: 282: HdfsTimeoutException: Connect to \"172.21.0.2:9866\" timeout\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tffi_closure_alloc\n",
      "\t@\tdlfree\n",
      "\t@\tdlmmap.constprop.0\n",
      "\t@\tu_set\n",
      "\t@\tUnknown\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tPyEval_EvalCodeEx\n",
      "\t@\tPyEval_EvalCode\n",
      "\t@\tbuiltin_exec\n",
      "\t@\tcfunction_vectorcall_FASTCALL\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tmethod_vectorcall_O\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\tPyObject_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tUnknown\n",
      "\n",
      "2023-10-02 16:31:17.901034, p3881, th140296688829504, INFO Abandoning block: [block pool ID: BP-559880233-172.21.0.5-1696238773587 block ID 1073741825_1001] for file /test.txt.\n",
      "2023-10-02 16:31:32.926364, p3881, th140296688829504, INFO RPC channel to \"localhost:8020\" got no response or idle for 10000 milliseconds, sending ping.\n",
      "2023-10-02 16:31:34.001476, p3881, th140296688829504, INFO Excluding invalid datanode: datanode(172.21.0.2) for block [block pool ID: BP-559880233-172.21.0.5-1696238773587 block ID 1073741825_1001] for file /test.txt\n",
      "2023-10-02 16:31:34.183830, p3881, th140296688829504, ERROR Failed to allocate a new empty block for file /test.txt, last block Null, excluded nodes [datanode(172.21.0.2)].\n",
      "NamenodeImpl.cpp: 277: File /test.txt could only be written to 0 of the 1 minReplication nodes. There are 1 datanode(s) running and 1 node(s) are excluded in this operation.\n",
      "\tat org.apache.hadoop.hdfs.server.blockmanagement.BlockManager.chooseTarget4NewBlock(BlockManager.java:2350)\n",
      "\tat org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.chooseTargetForNewBlock(FSDirWriteFileOp.java:294)\n",
      "\tat org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getAdditionalBlock(FSNamesystem.java:2989)\n",
      "\tat org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.addBlock(NameNodeRpcServer.java:912)\n",
      "\tat org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.addBlock(ClientNamenodeProtocolServerSideTranslatorPB.java:595)\n",
      "\tat org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)\n",
      "\tat org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:621)\n",
      "\tat org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:589)\n",
      "\tat org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:573)\n",
      "\tat org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1227)\n",
      "\tat org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:1094)\n",
      "\tat org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:1017)\n",
      "\tat java.security.AccessController.doPrivileged(Native Method)\n",
      "\tat javax.security.auth.Subject.doAs(Subject.java:422)\n",
      "\tat org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1899)\n",
      "\tat org.apache.hadoop.ipc.Server$Handler.run(Server.java:3048)\n",
      "\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tffi_closure_alloc\n",
      "\t@\tdlfree\n",
      "\t@\tdlmmap.constprop.0\n",
      "\t@\tu_set\n",
      "\t@\tUnknown\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tPyEval_EvalCodeEx\n",
      "\t@\tPyEval_EvalCode\n",
      "\t@\tbuiltin_exec\n",
      "\t@\tcfunction_vectorcall_FASTCALL\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tmethod_vectorcall_O\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\tPyObject_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\n",
      "2023-10-02 16:31:34.183925, p3881, th140296688829504, ERROR Handle Exception: NamenodeImpl.cpp: 277: File /test.txt could only be written to 0 of the 1 minReplication nodes. There are 1 datanode(s) running and 1 node(s) are excluded in this operation.\n",
      "\tat org.apache.hadoop.hdfs.server.blockmanagement.BlockManager.chooseTarget4NewBlock(BlockManager.java:2350)\n",
      "\tat org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.chooseTargetForNewBlock(FSDirWriteFileOp.java:294)\n",
      "\tat org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getAdditionalBlock(FSNamesystem.java:2989)\n",
      "\tat org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.addBlock(NameNodeRpcServer.java:912)\n",
      "\tat org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.addBlock(ClientNamenodeProtocolServerSideTranslatorPB.java:595)\n",
      "\tat org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)\n",
      "\tat org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:621)\n",
      "\tat org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:589)\n",
      "\tat org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:573)\n",
      "\tat org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1227)\n",
      "\tat org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:1094)\n",
      "\tat org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:1017)\n",
      "\tat java.security.AccessController.doPrivileged(Native Method)\n",
      "\tat javax.security.auth.Subject.doAs(Subject.java:422)\n",
      "\tat org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1899)\n",
      "\tat org.apache.hadoop.ipc.Server$Handler.run(Server.java:3048)\n",
      "\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tffi_closure_alloc\n",
      "\t@\tdlfree\n",
      "\t@\tdlmmap.constprop.0\n",
      "\t@\tu_set\n",
      "\t@\tUnknown\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tPyEval_EvalCodeEx\n",
      "\t@\tPyEval_EvalCode\n",
      "\t@\tbuiltin_exec\n",
      "\t@\tcfunction_vectorcall_FASTCALL\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tmethod_vectorcall_O\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\tPyObject_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    hdfs.put('test.txt','/test.txt')\n",
    "except Exception as e:\n",
    "    print(e)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-09-28 15:47:14.037917, p680, th139982298342464, ERROR cannot setup block reader for Block: [block pool ID: BP-435783800-172.19.0.4-1695890191831 block ID 1073741826_1002] file /test.txt on Datanode: 40d68dbd7a95(172.19.0.3).\n",
      "RemoteBlockReader.cpp: 122: HdfsIOException: RemoteBlockReader: Failed to connect to 40d68dbd7a95(172.19.0.3)\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tffi_closure_alloc\n",
      "\t@\tdlfree\n",
      "\t@\tdlmmap.constprop.0\n",
      "\t@\tu_set\n",
      "\t@\tunpickle\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tPyEval_EvalCodeEx\n",
      "\t@\tPyEval_EvalCode\n",
      "\t@\tbuiltin_exec\n",
      "\t@\tcfunction_vectorcall_FASTCALL\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tmethod_vectorcall_O\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\tPyObject_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\tcontext_run\n",
      "\t@\tcfunction_vectorcall_FASTCALL_KEYWORDS\n",
      "\t@\tPyVectorcall_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "Caused by\n",
      "TcpSocket.cpp: 282: HdfsTimeoutException: Connect to \"172.19.0.3:9866\" timeout\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tffi_closure_alloc\n",
      "\t@\tdlfree\n",
      "\t@\tdlmmap.constprop.0\n",
      "\t@\tu_set\n",
      "\t@\tunpickle\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tPyEval_EvalCodeEx\n",
      "\t@\tPyEval_EvalCode\n",
      "\t@\tbuiltin_exec\n",
      "\t@\tcfunction_vectorcall_FASTCALL\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tmethod_vectorcall_O\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\tPyObject_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\tcontext_run\n",
      "\t@\tcfunction_vectorcall_FASTCALL_KEYWORDS\n",
      "\t@\tPyVectorcall_Call\n",
      "\n",
      "retry another node\n",
      "2023-09-28 15:47:14.187201, p680, th139982298342464, ERROR InputStreamImpl: failed to read Block: [block pool ID: BP-435783800-172.19.0.4-1695890191831 block ID 1073741826_1002] file /test.txt, \n",
      "InputStreamImpl.cpp: 329: HdfsIOException: InputStreamImpl: all nodes have been tried and no valid replica can be read for Block: [block pool ID: BP-435783800-172.19.0.4-1695890191831 block ID 1073741826_1002].\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tffi_closure_alloc\n",
      "\t@\tdlfree\n",
      "\t@\tdlmmap.constprop.0\n",
      "\t@\tu_set\n",
      "\t@\tunpickle\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tPyEval_EvalCodeEx\n",
      "\t@\tPyEval_EvalCode\n",
      "\t@\tbuiltin_exec\n",
      "\t@\tcfunction_vectorcall_FASTCALL\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tmethod_vectorcall_O\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\tPyObject_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\tcontext_run\n",
      "\t@\tcfunction_vectorcall_FASTCALL_KEYWORDS\n",
      "\t@\tPyVectorcall_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "Caused by\n",
      "RemoteBlockReader.cpp: 122: HdfsIOException: RemoteBlockReader: Failed to connect to 40d68dbd7a95(172.19.0.3)\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tffi_closure_alloc\n",
      "\t@\tdlfree\n",
      "\t@\tdlmmap.constprop.0\n",
      "\t@\tu_set\n",
      "\t@\tunpickle\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tPyEval_EvalCodeEx\n",
      "\t@\tPyEval_EvalCode\n",
      "\t@\tbuiltin_exec\n",
      "\t@\tcfunction_vectorcall_FASTCALL\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tmethod_vectorcall_O\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\tPyObject_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\tcontext_run\n",
      "\t@\tcfunction_vectorcall_FASTCALL_KEYWORDS\n",
      "\t@\tPyVectorcall_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "Caused by\n",
      "TcpSocket.cpp: 282: HdfsTimeoutException: Connect to \"172.19.0.3:9866\" timeout\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tffi_closure_alloc\n",
      "\t@\tdlfree\n",
      "\t@\tdlmmap.constprop.0\n",
      "\t@\tu_set\n",
      "\t@\tunpickle\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tPyEval_EvalCodeEx\n",
      "\t@\tPyEval_EvalCode\n",
      "\t@\tbuiltin_exec\n",
      "\t@\tcfunction_vectorcall_FASTCALL\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tmethod_vectorcall_O\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\tPyObject_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\tcontext_run\n",
      "\t@\tcfunction_vectorcall_FASTCALL_KEYWORDS\n",
      "\t@\tPyVectorcall_Call\n",
      ", retry after updating block informations.\n",
      "2023-09-28 15:49:32.271301, p680, th139982298342464, ERROR cannot setup block reader for Block: [block pool ID: BP-435783800-172.19.0.4-1695890191831 block ID 1073741826_1002] file /test.txt on Datanode: 40d68dbd7a95(172.19.0.3).\n",
      "RemoteBlockReader.cpp: 122: HdfsIOException: RemoteBlockReader: Failed to connect to 40d68dbd7a95(172.19.0.3)\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tffi_closure_alloc\n",
      "\t@\tdlfree\n",
      "\t@\tdlmmap.constprop.0\n",
      "\t@\tu_set\n",
      "\t@\tunpickle\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tPyEval_EvalCodeEx\n",
      "\t@\tPyEval_EvalCode\n",
      "\t@\tbuiltin_exec\n",
      "\t@\tcfunction_vectorcall_FASTCALL\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tmethod_vectorcall_O\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\tPyObject_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\tcontext_run\n",
      "\t@\tcfunction_vectorcall_FASTCALL_KEYWORDS\n",
      "\t@\tPyVectorcall_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "Caused by\n",
      "TcpSocket.cpp: 282: HdfsTimeoutException: Connect to \"172.19.0.3:9866\" timeout\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tffi_closure_alloc\n",
      "\t@\tdlfree\n",
      "\t@\tdlmmap.constprop.0\n",
      "\t@\tu_set\n",
      "\t@\tunpickle\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tPyEval_EvalCodeEx\n",
      "\t@\tPyEval_EvalCode\n",
      "\t@\tbuiltin_exec\n",
      "\t@\tcfunction_vectorcall_FASTCALL\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tmethod_vectorcall_O\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\tPyObject_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\tcontext_run\n",
      "\t@\tcfunction_vectorcall_FASTCALL_KEYWORDS\n",
      "\t@\tPyVectorcall_Call\n",
      "\n",
      "retry another node\n",
      "2023-09-28 15:49:32.408364, p680, th139982298342464, ERROR InputStreamImpl: failed to read Block: [block pool ID: BP-435783800-172.19.0.4-1695890191831 block ID 1073741826_1002] file /test.txt, \n",
      "InputStreamImpl.cpp: 329: HdfsIOException: InputStreamImpl: all nodes have been tried and no valid replica can be read for Block: [block pool ID: BP-435783800-172.19.0.4-1695890191831 block ID 1073741826_1002].\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tffi_closure_alloc\n",
      "\t@\tdlfree\n",
      "\t@\tdlmmap.constprop.0\n",
      "\t@\tu_set\n",
      "\t@\tunpickle\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tPyEval_EvalCodeEx\n",
      "\t@\tPyEval_EvalCode\n",
      "\t@\tbuiltin_exec\n",
      "\t@\tcfunction_vectorcall_FASTCALL\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tmethod_vectorcall_O\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\tPyObject_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\tcontext_run\n",
      "\t@\tcfunction_vectorcall_FASTCALL_KEYWORDS\n",
      "\t@\tPyVectorcall_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "Caused by\n",
      "RemoteBlockReader.cpp: 122: HdfsIOException: RemoteBlockReader: Failed to connect to 40d68dbd7a95(172.19.0.3)\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tffi_closure_alloc\n",
      "\t@\tdlfree\n",
      "\t@\tdlmmap.constprop.0\n",
      "\t@\tu_set\n",
      "\t@\tunpickle\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tPyEval_EvalCodeEx\n",
      "\t@\tPyEval_EvalCode\n",
      "\t@\tbuiltin_exec\n",
      "\t@\tcfunction_vectorcall_FASTCALL\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tmethod_vectorcall_O\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\tPyObject_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\tcontext_run\n",
      "\t@\tcfunction_vectorcall_FASTCALL_KEYWORDS\n",
      "\t@\tPyVectorcall_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "Caused by\n",
      "TcpSocket.cpp: 282: HdfsTimeoutException: Connect to \"172.19.0.3:9866\" timeout\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tffi_closure_alloc\n",
      "\t@\tdlfree\n",
      "\t@\tdlmmap.constprop.0\n",
      "\t@\tu_set\n",
      "\t@\tunpickle\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tPyEval_EvalCodeEx\n",
      "\t@\tPyEval_EvalCode\n",
      "\t@\tbuiltin_exec\n",
      "\t@\tcfunction_vectorcall_FASTCALL\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tmethod_vectorcall_O\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\tPyObject_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\tcontext_run\n",
      "\t@\tcfunction_vectorcall_FASTCALL_KEYWORDS\n",
      "\t@\tPyVectorcall_Call\n",
      ", retry after updating block informations.\n",
      "2023-09-28 15:51:50.508712, p680, th139982298342464, ERROR cannot setup block reader for Block: [block pool ID: BP-435783800-172.19.0.4-1695890191831 block ID 1073741826_1002] file /test.txt on Datanode: 40d68dbd7a95(172.19.0.3).\n",
      "RemoteBlockReader.cpp: 122: HdfsIOException: RemoteBlockReader: Failed to connect to 40d68dbd7a95(172.19.0.3)\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tffi_closure_alloc\n",
      "\t@\tdlfree\n",
      "\t@\tdlmmap.constprop.0\n",
      "\t@\tu_set\n",
      "\t@\tunpickle\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tPyEval_EvalCodeEx\n",
      "\t@\tPyEval_EvalCode\n",
      "\t@\tbuiltin_exec\n",
      "\t@\tcfunction_vectorcall_FASTCALL\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tmethod_vectorcall_O\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\tPyObject_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\tcontext_run\n",
      "\t@\tcfunction_vectorcall_FASTCALL_KEYWORDS\n",
      "\t@\tPyVectorcall_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "Caused by\n",
      "TcpSocket.cpp: 282: HdfsTimeoutException: Connect to \"172.19.0.3:9866\" timeout\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tffi_closure_alloc\n",
      "\t@\tdlfree\n",
      "\t@\tdlmmap.constprop.0\n",
      "\t@\tu_set\n",
      "\t@\tunpickle\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tPyEval_EvalCodeEx\n",
      "\t@\tPyEval_EvalCode\n",
      "\t@\tbuiltin_exec\n",
      "\t@\tcfunction_vectorcall_FASTCALL\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tmethod_vectorcall_O\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\tPyObject_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\tcontext_run\n",
      "\t@\tcfunction_vectorcall_FASTCALL_KEYWORDS\n",
      "\t@\tPyVectorcall_Call\n",
      "\n",
      "retry another node\n",
      "2023-09-28 15:51:50.603691, p680, th139982298342464, ERROR InputStreamImpl: failed to read Block: [block pool ID: BP-435783800-172.19.0.4-1695890191831 block ID 1073741826_1002] file /test.txt, \n",
      "InputStreamImpl.cpp: 329: HdfsIOException: InputStreamImpl: all nodes have been tried and no valid replica can be read for Block: [block pool ID: BP-435783800-172.19.0.4-1695890191831 block ID 1073741826_1002].\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tffi_closure_alloc\n",
      "\t@\tdlfree\n",
      "\t@\tdlmmap.constprop.0\n",
      "\t@\tu_set\n",
      "\t@\tunpickle\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tPyEval_EvalCodeEx\n",
      "\t@\tPyEval_EvalCode\n",
      "\t@\tbuiltin_exec\n",
      "\t@\tcfunction_vectorcall_FASTCALL\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tmethod_vectorcall_O\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\tPyObject_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\tcontext_run\n",
      "\t@\tcfunction_vectorcall_FASTCALL_KEYWORDS\n",
      "\t@\tPyVectorcall_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "Caused by\n",
      "RemoteBlockReader.cpp: 122: HdfsIOException: RemoteBlockReader: Failed to connect to 40d68dbd7a95(172.19.0.3)\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tffi_closure_alloc\n",
      "\t@\tdlfree\n",
      "\t@\tdlmmap.constprop.0\n",
      "\t@\tu_set\n",
      "\t@\tunpickle\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tPyEval_EvalCodeEx\n",
      "\t@\tPyEval_EvalCode\n",
      "\t@\tbuiltin_exec\n",
      "\t@\tcfunction_vectorcall_FASTCALL\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tmethod_vectorcall_O\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\tPyObject_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\tcontext_run\n",
      "\t@\tcfunction_vectorcall_FASTCALL_KEYWORDS\n",
      "\t@\tPyVectorcall_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "Caused by\n",
      "TcpSocket.cpp: 282: HdfsTimeoutException: Connect to \"172.19.0.3:9866\" timeout\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\tffi_closure_alloc\n",
      "\t@\tdlfree\n",
      "\t@\tdlmmap.constprop.0\n",
      "\t@\tu_set\n",
      "\t@\tunpickle\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tPyEval_EvalCodeEx\n",
      "\t@\tPyEval_EvalCode\n",
      "\t@\tbuiltin_exec\n",
      "\t@\tcfunction_vectorcall_FASTCALL\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tmethod_vectorcall_O\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\t_PyFunction_Vectorcall\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\tPyObject_Call\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\t_PyEval_EvalCodeWithName\n",
      "\t@\tmethod_vectorcall\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\t_PyEval_EvalFrameDefault\n",
      "\t@\tgen_send_ex\n",
      "\t@\tUnknown\n",
      "\t@\tUnknown\n",
      "\t@\t_PyObject_MakeTpCall\n",
      "\t@\tcontext_run\n",
      "\t@\tcfunction_vectorcall_FASTCALL_KEYWORDS\n",
      "\t@\tPyVectorcall_Call\n",
      ", retry after updating block informations.\n"
     ]
    }
   ],
   "source": [
    "with hdfs.open(\"/test.txt\", \"rb\") as file:\n",
    "    data = file.read(1000)\n",
    "\n",
    "data"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "hdfs",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.18"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
